/* gc_presets.h —— 自动生成，请勿手改
 *
 * ★ 「原版 + 7 档梯度」预设体系
 *
 * 【设计依据】联网查证的结论：
 *   · 内存池/模型信息池调小 ⇒ 更卡（池满会频繁卸载重载模型）
 *     PoolManager 官方: "WARNING Performance heavy when using lower values!"
 *   · 真正省 CPU 的是：密度倍率 / 数量上限 / 刷新率 / 剔除范围 / 间距
 *   · 人口密度实测影响最大（0→10/10 约差 11%）
 *
 * 档位（每档覆盖 79 项）：
 *   t=0.00  极限省电   最省 CPU
 *   t=0.16  省电
 *   t=0.34  均衡
 *   t=0.50  均衡+
 *   t=0.68  画质
 *   t=0.84  高画质
 *   t=1.00  极限       最强画质
 *
 * 「原版」= 移植作者原始值，用于一键还原。
 */
#ifndef GC_PRESETS_H
#define GC_PRESETS_H

#define GC_CAP_DEFAULT   7837      /* 原 on_disk（实际容量用 gc_rpf_room 算） */
#ifndef GC_ON_DISK_MAX
#define GC_ON_DISK_MAX   16777215u
#endif

/* 一个旋钮赋值 */
typedef struct { const char *key; int value; } GcKnob;

/* 一套预设 */
typedef struct {
    const char *name;
    const char *tag;
    const char *desc;
    const char *name_en;   /* ★ v6.3.2: 英文名 */
    const char *tag_en;
    const char *desc_en;
    const GcKnob *knobs;
    int n_knobs;
    int t_pct;             /* 档位系数 ×100（原版 = -1） */
} GcPreset;

/* ---- 原版 [官方原始] ---- */
static const GcKnob GC_PRESET_ORIGINAL_KNOBS[] = {
    { "AmbientPedsMultiplier", 70 },
    { "AmbientPedsMultiplier_Base", 50 },
    { "PedPopulationFrameRate", 25 },
    { "PedPopulationFrameRate_Base", 20 },
    { "PedsForVehicles", 50 },
    { "PedsForVehicles_Base", 50 },
    { "ScenarioPedsMultiplier", 70 },
    { "ScenarioPedsMultiplier_Base", 50 },
    { "VehicleAmbientDensityMultiplier", 70 },
    { "VehicleAmbientDensityMultiplier_Base", 45 },
    { "VehicleLowPrioParkedDensityMultiplier", 50 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 30 },
    { "VehicleParkedDensityMultiplier", 60 },
    { "VehicleParkedDensityMultiplier_Base", 35 },
    { "VehiclePopulationFrameRate", 25 },
    { "VehiclePopulationFrameRate_Base", 20 },
    { "MaxTotalPeds", 50 },
    { "MaxTotalPeds_Base", 45 },
    { "VehicleParkedUpperLimit", 50 },
    { "VehicleParkedUpperLimit_Base", 28 },
    { "VehicleUpperLimit", 48 },
    { "VehicleUpperLimit_Base", 24 },
    { "PedMemoryMultiplier", 150 },
    { "VehicleMemoryMultiplier", 100 },
    { "VehicleSpacing_1", 172 },
    { "VehicleSpacing_10", 34 },
    { "VehicleSpacing_11", 27 },
    { "VehicleSpacing_12", 22 },
    { "VehicleSpacing_13", 20 },
    { "VehicleSpacing_14", 19 },
    { "VehicleSpacing_15", 18 },
    { "VehicleSpacing_2", 150 },
    { "VehicleSpacing_3", 129 },
    { "VehicleSpacing_4", 110 },
    { "VehicleSpacing_5", 88 },
    { "VehicleSpacing_6", 55 },
    { "VehicleSpacing_7", 52 },
    { "VehicleSpacing_8", 45 },
    { "VehicleSpacing_9", 40 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 5 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 3 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 极限省电 [最省CPU] ---- */
static const GcKnob GC_PRESET_ULTRA_SAVE_KNOBS[] = {
    { "AmbientPedsMultiplier", 42 },
    { "AmbientPedsMultiplier_Base", 30 },
    { "PedPopulationFrameRate", 12 },
    { "PedPopulationFrameRate_Base", 10 },
    { "PedsForVehicles", 30 },
    { "PedsForVehicles_Base", 30 },
    { "ScenarioPedsMultiplier", 42 },
    { "ScenarioPedsMultiplier_Base", 30 },
    { "VehicleAmbientDensityMultiplier", 42 },
    { "VehicleAmbientDensityMultiplier_Base", 27 },
    { "VehicleLowPrioParkedDensityMultiplier", 30 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 18 },
    { "VehicleParkedDensityMultiplier", 36 },
    { "VehicleParkedDensityMultiplier_Base", 21 },
    { "VehiclePopulationFrameRate", 12 },
    { "VehiclePopulationFrameRate_Base", 10 },
    { "MaxTotalPeds", 35 },
    { "MaxTotalPeds_Base", 32 },
    { "VehicleParkedUpperLimit", 35 },
    { "VehicleParkedUpperLimit_Base", 20 },
    { "VehicleUpperLimit", 34 },
    { "VehicleUpperLimit_Base", 17 },
    { "PedMemoryMultiplier", 110 },
    { "VehicleMemoryMultiplier", 75 },
    { "VehicleSpacing_1", 215 },
    { "VehicleSpacing_10", 43 },
    { "VehicleSpacing_11", 34 },
    { "VehicleSpacing_12", 28 },
    { "VehicleSpacing_13", 25 },
    { "VehicleSpacing_14", 24 },
    { "VehicleSpacing_15", 23 },
    { "VehicleSpacing_2", 188 },
    { "VehicleSpacing_3", 161 },
    { "VehicleSpacing_4", 138 },
    { "VehicleSpacing_5", 110 },
    { "VehicleSpacing_6", 69 },
    { "VehicleSpacing_7", 65 },
    { "VehicleSpacing_8", 56 },
    { "VehicleSpacing_9", 50 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 3 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 2 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 省电 [续航优先] ---- */
static const GcKnob GC_PRESET_POWERSAVE_KNOBS[] = {
    { "AmbientPedsMultiplier", 46 },
    { "AmbientPedsMultiplier_Base", 33 },
    { "PedPopulationFrameRate", 14 },
    { "PedPopulationFrameRate_Base", 12 },
    { "PedsForVehicles", 33 },
    { "PedsForVehicles_Base", 33 },
    { "ScenarioPedsMultiplier", 46 },
    { "ScenarioPedsMultiplier_Base", 33 },
    { "VehicleAmbientDensityMultiplier", 46 },
    { "VehicleAmbientDensityMultiplier_Base", 30 },
    { "VehicleLowPrioParkedDensityMultiplier", 33 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 20 },
    { "VehicleParkedDensityMultiplier", 40 },
    { "VehicleParkedDensityMultiplier_Base", 23 },
    { "VehiclePopulationFrameRate", 14 },
    { "VehiclePopulationFrameRate_Base", 12 },
    { "MaxTotalPeds", 37 },
    { "MaxTotalPeds_Base", 34 },
    { "VehicleParkedUpperLimit", 37 },
    { "VehicleParkedUpperLimit_Base", 21 },
    { "VehicleUpperLimit", 36 },
    { "VehicleUpperLimit_Base", 18 },
    { "PedMemoryMultiplier", 116 },
    { "VehicleMemoryMultiplier", 79 },
    { "VehicleSpacing_1", 208 },
    { "VehicleSpacing_10", 42 },
    { "VehicleSpacing_11", 33 },
    { "VehicleSpacing_12", 27 },
    { "VehicleSpacing_13", 24 },
    { "VehicleSpacing_14", 23 },
    { "VehicleSpacing_15", 22 },
    { "VehicleSpacing_2", 182 },
    { "VehicleSpacing_3", 156 },
    { "VehicleSpacing_4", 134 },
    { "VehicleSpacing_5", 106 },
    { "VehicleSpacing_6", 67 },
    { "VehicleSpacing_7", 63 },
    { "VehicleSpacing_8", 54 },
    { "VehicleSpacing_9", 48 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 3 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 2 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 均衡 [最安全] ---- */
static const GcKnob GC_PRESET_BALANCED_KNOBS[] = {
    { "AmbientPedsMultiplier", 52 },
    { "AmbientPedsMultiplier_Base", 37 },
    { "PedPopulationFrameRate", 16 },
    { "PedPopulationFrameRate_Base", 13 },
    { "PedsForVehicles", 37 },
    { "PedsForVehicles_Base", 37 },
    { "ScenarioPedsMultiplier", 52 },
    { "ScenarioPedsMultiplier_Base", 37 },
    { "VehicleAmbientDensityMultiplier", 52 },
    { "VehicleAmbientDensityMultiplier_Base", 33 },
    { "VehicleLowPrioParkedDensityMultiplier", 37 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 22 },
    { "VehicleParkedDensityMultiplier", 44 },
    { "VehicleParkedDensityMultiplier_Base", 26 },
    { "VehiclePopulationFrameRate", 16 },
    { "VehiclePopulationFrameRate_Base", 13 },
    { "MaxTotalPeds", 40 },
    { "MaxTotalPeds_Base", 36 },
    { "VehicleParkedUpperLimit", 40 },
    { "VehicleParkedUpperLimit_Base", 23 },
    { "VehicleUpperLimit", 39 },
    { "VehicleUpperLimit_Base", 19 },
    { "PedMemoryMultiplier", 124 },
    { "VehicleMemoryMultiplier", 84 },
    { "VehicleSpacing_1", 200 },
    { "VehicleSpacing_10", 40 },
    { "VehicleSpacing_11", 32 },
    { "VehicleSpacing_12", 26 },
    { "VehicleSpacing_13", 23 },
    { "VehicleSpacing_14", 22 },
    { "VehicleSpacing_15", 21 },
    { "VehicleSpacing_2", 175 },
    { "VehicleSpacing_3", 150 },
    { "VehicleSpacing_4", 128 },
    { "VehicleSpacing_5", 103 },
    { "VehicleSpacing_6", 64 },
    { "VehicleSpacing_7", 61 },
    { "VehicleSpacing_8", 52 },
    { "VehicleSpacing_9", 47 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 4 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 2 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 均衡+ [推荐] ---- */
static const GcKnob GC_PRESET_BALANCED_PLUS_KNOBS[] = {
    { "AmbientPedsMultiplier", 56 },
    { "AmbientPedsMultiplier_Base", 40 },
    { "PedPopulationFrameRate", 18 },
    { "PedPopulationFrameRate_Base", 15 },
    { "PedsForVehicles", 40 },
    { "PedsForVehicles_Base", 40 },
    { "ScenarioPedsMultiplier", 56 },
    { "ScenarioPedsMultiplier_Base", 40 },
    { "VehicleAmbientDensityMultiplier", 56 },
    { "VehicleAmbientDensityMultiplier_Base", 36 },
    { "VehicleLowPrioParkedDensityMultiplier", 40 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 24 },
    { "VehicleParkedDensityMultiplier", 48 },
    { "VehicleParkedDensityMultiplier_Base", 28 },
    { "VehiclePopulationFrameRate", 18 },
    { "VehiclePopulationFrameRate_Base", 15 },
    { "MaxTotalPeds", 42 },
    { "MaxTotalPeds_Base", 38 },
    { "VehicleParkedUpperLimit", 42 },
    { "VehicleParkedUpperLimit_Base", 24 },
    { "VehicleUpperLimit", 41 },
    { "VehicleUpperLimit_Base", 20 },
    { "PedMemoryMultiplier", 130 },
    { "VehicleMemoryMultiplier", 88 },
    { "VehicleSpacing_1", 194 },
    { "VehicleSpacing_10", 38 },
    { "VehicleSpacing_11", 30 },
    { "VehicleSpacing_12", 25 },
    { "VehicleSpacing_13", 22 },
    { "VehicleSpacing_14", 22 },
    { "VehicleSpacing_15", 20 },
    { "VehicleSpacing_2", 169 },
    { "VehicleSpacing_3", 145 },
    { "VehicleSpacing_4", 124 },
    { "VehicleSpacing_5", 99 },
    { "VehicleSpacing_6", 62 },
    { "VehicleSpacing_7", 58 },
    { "VehicleSpacing_8", 50 },
    { "VehicleSpacing_9", 45 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 4 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 2 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 画质 [画质优先] ---- */
static const GcKnob GC_PRESET_QUALITY_KNOBS[] = {
    { "AmbientPedsMultiplier", 61 },
    { "AmbientPedsMultiplier_Base", 44 },
    { "PedPopulationFrameRate", 21 },
    { "PedPopulationFrameRate_Base", 17 },
    { "PedsForVehicles", 44 },
    { "PedsForVehicles_Base", 44 },
    { "ScenarioPedsMultiplier", 61 },
    { "ScenarioPedsMultiplier_Base", 44 },
    { "VehicleAmbientDensityMultiplier", 61 },
    { "VehicleAmbientDensityMultiplier_Base", 39 },
    { "VehicleLowPrioParkedDensityMultiplier", 44 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 26 },
    { "VehicleParkedDensityMultiplier", 52 },
    { "VehicleParkedDensityMultiplier_Base", 31 },
    { "VehiclePopulationFrameRate", 21 },
    { "VehiclePopulationFrameRate_Base", 17 },
    { "MaxTotalPeds", 45 },
    { "MaxTotalPeds_Base", 41 },
    { "VehicleParkedUpperLimit", 45 },
    { "VehicleParkedUpperLimit_Base", 25 },
    { "VehicleUpperLimit", 44 },
    { "VehicleUpperLimit_Base", 22 },
    { "PedMemoryMultiplier", 137 },
    { "VehicleMemoryMultiplier", 92 },
    { "VehicleSpacing_1", 186 },
    { "VehicleSpacing_10", 37 },
    { "VehicleSpacing_11", 29 },
    { "VehicleSpacing_12", 24 },
    { "VehicleSpacing_13", 22 },
    { "VehicleSpacing_14", 21 },
    { "VehicleSpacing_15", 20 },
    { "VehicleSpacing_2", 162 },
    { "VehicleSpacing_3", 139 },
    { "VehicleSpacing_4", 119 },
    { "VehicleSpacing_5", 95 },
    { "VehicleSpacing_6", 59 },
    { "VehicleSpacing_7", 56 },
    { "VehicleSpacing_8", 49 },
    { "VehicleSpacing_9", 43 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 4 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 3 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 高画质 [画质优先] ---- */
static const GcKnob GC_PRESET_HIGH_KNOBS[] = {
    { "AmbientPedsMultiplier", 66 },
    { "AmbientPedsMultiplier_Base", 47 },
    { "PedPopulationFrameRate", 23 },
    { "PedPopulationFrameRate_Base", 18 },
    { "PedsForVehicles", 47 },
    { "PedsForVehicles_Base", 47 },
    { "ScenarioPedsMultiplier", 66 },
    { "ScenarioPedsMultiplier_Base", 47 },
    { "VehicleAmbientDensityMultiplier", 66 },
    { "VehicleAmbientDensityMultiplier_Base", 42 },
    { "VehicleLowPrioParkedDensityMultiplier", 47 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 28 },
    { "VehicleParkedDensityMultiplier", 56 },
    { "VehicleParkedDensityMultiplier_Base", 33 },
    { "VehiclePopulationFrameRate", 23 },
    { "VehiclePopulationFrameRate_Base", 18 },
    { "MaxTotalPeds", 48 },
    { "MaxTotalPeds_Base", 43 },
    { "VehicleParkedUpperLimit", 48 },
    { "VehicleParkedUpperLimit_Base", 27 },
    { "VehicleUpperLimit", 46 },
    { "VehicleUpperLimit_Base", 23 },
    { "PedMemoryMultiplier", 144 },
    { "VehicleMemoryMultiplier", 96 },
    { "VehicleSpacing_1", 179 },
    { "VehicleSpacing_10", 35 },
    { "VehicleSpacing_11", 28 },
    { "VehicleSpacing_12", 23 },
    { "VehicleSpacing_13", 21 },
    { "VehicleSpacing_14", 20 },
    { "VehicleSpacing_15", 19 },
    { "VehicleSpacing_2", 156 },
    { "VehicleSpacing_3", 134 },
    { "VehicleSpacing_4", 114 },
    { "VehicleSpacing_5", 92 },
    { "VehicleSpacing_6", 57 },
    { "VehicleSpacing_7", 54 },
    { "VehicleSpacing_8", 47 },
    { "VehicleSpacing_9", 42 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 5 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 3 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 极限 [仅超频机] ---- */
static const GcKnob GC_PRESET_EXTREME_KNOBS[] = {
    { "AmbientPedsMultiplier", 70 },
    { "AmbientPedsMultiplier_Base", 50 },
    { "PedPopulationFrameRate", 25 },
    { "PedPopulationFrameRate_Base", 20 },
    { "PedsForVehicles", 50 },
    { "PedsForVehicles_Base", 50 },
    { "ScenarioPedsMultiplier", 70 },
    { "ScenarioPedsMultiplier_Base", 50 },
    { "VehicleAmbientDensityMultiplier", 70 },
    { "VehicleAmbientDensityMultiplier_Base", 45 },
    { "VehicleLowPrioParkedDensityMultiplier", 50 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 30 },
    { "VehicleParkedDensityMultiplier", 60 },
    { "VehicleParkedDensityMultiplier_Base", 35 },
    { "VehiclePopulationFrameRate", 25 },
    { "VehiclePopulationFrameRate_Base", 20 },
    { "MaxTotalPeds", 50 },
    { "MaxTotalPeds_Base", 45 },
    { "VehicleParkedUpperLimit", 50 },
    { "VehicleParkedUpperLimit_Base", 28 },
    { "VehicleUpperLimit", 48 },
    { "VehicleUpperLimit_Base", 24 },
    { "PedMemoryMultiplier", 150 },
    { "VehicleMemoryMultiplier", 100 },
    { "VehicleSpacing_1", 172 },
    { "VehicleSpacing_10", 34 },
    { "VehicleSpacing_11", 27 },
    { "VehicleSpacing_12", 22 },
    { "VehicleSpacing_13", 20 },
    { "VehicleSpacing_14", 19 },
    { "VehicleSpacing_15", 18 },
    { "VehicleSpacing_2", 150 },
    { "VehicleSpacing_3", 129 },
    { "VehicleSpacing_4", 110 },
    { "VehicleSpacing_5", 88 },
    { "VehicleSpacing_6", 55 },
    { "VehicleSpacing_7", 52 },
    { "VehicleSpacing_8", 45 },
    { "VehicleSpacing_9", 40 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 5 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 3 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 测·仅密度 [诊断] ---- */
static const GcKnob GC_PRESET_DIAG_DENSITY_KNOBS[] = {
    { "AmbientPedsMultiplier", 42 },
    { "AmbientPedsMultiplier_Base", 30 },
    { "PedPopulationFrameRate", 25 },
    { "PedPopulationFrameRate_Base", 20 },
    { "PedsForVehicles", 30 },
    { "PedsForVehicles_Base", 30 },
    { "ScenarioPedsMultiplier", 42 },
    { "ScenarioPedsMultiplier_Base", 30 },
    { "VehicleAmbientDensityMultiplier", 42 },
    { "VehicleAmbientDensityMultiplier_Base", 27 },
    { "VehicleLowPrioParkedDensityMultiplier", 30 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 18 },
    { "VehicleParkedDensityMultiplier", 36 },
    { "VehicleParkedDensityMultiplier_Base", 21 },
    { "VehiclePopulationFrameRate", 25 },
    { "VehiclePopulationFrameRate_Base", 20 },
    { "MaxTotalPeds", 50 },
    { "MaxTotalPeds_Base", 45 },
    { "VehicleParkedUpperLimit", 50 },
    { "VehicleParkedUpperLimit_Base", 28 },
    { "VehicleUpperLimit", 48 },
    { "VehicleUpperLimit_Base", 24 },
    { "PedMemoryMultiplier", 150 },
    { "VehicleMemoryMultiplier", 100 },
    { "VehicleSpacing_1", 172 },
    { "VehicleSpacing_10", 34 },
    { "VehicleSpacing_11", 27 },
    { "VehicleSpacing_12", 22 },
    { "VehicleSpacing_13", 20 },
    { "VehicleSpacing_14", 19 },
    { "VehicleSpacing_15", 18 },
    { "VehicleSpacing_2", 150 },
    { "VehicleSpacing_3", 129 },
    { "VehicleSpacing_4", 110 },
    { "VehicleSpacing_5", 88 },
    { "VehicleSpacing_6", 55 },
    { "VehicleSpacing_7", 52 },
    { "VehicleSpacing_8", 45 },
    { "VehicleSpacing_9", 40 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 5 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 3 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 测·仅刷新 [诊断] ---- */
static const GcKnob GC_PRESET_DIAG_RATE_KNOBS[] = {
    { "AmbientPedsMultiplier", 70 },
    { "AmbientPedsMultiplier_Base", 50 },
    { "PedPopulationFrameRate", 12 },
    { "PedPopulationFrameRate_Base", 10 },
    { "PedsForVehicles", 50 },
    { "PedsForVehicles_Base", 50 },
    { "ScenarioPedsMultiplier", 70 },
    { "ScenarioPedsMultiplier_Base", 50 },
    { "VehicleAmbientDensityMultiplier", 70 },
    { "VehicleAmbientDensityMultiplier_Base", 45 },
    { "VehicleLowPrioParkedDensityMultiplier", 50 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 30 },
    { "VehicleParkedDensityMultiplier", 60 },
    { "VehicleParkedDensityMultiplier_Base", 35 },
    { "VehiclePopulationFrameRate", 12 },
    { "VehiclePopulationFrameRate_Base", 10 },
    { "MaxTotalPeds", 50 },
    { "MaxTotalPeds_Base", 45 },
    { "VehicleParkedUpperLimit", 50 },
    { "VehicleParkedUpperLimit_Base", 28 },
    { "VehicleUpperLimit", 48 },
    { "VehicleUpperLimit_Base", 24 },
    { "PedMemoryMultiplier", 150 },
    { "VehicleMemoryMultiplier", 100 },
    { "VehicleSpacing_1", 172 },
    { "VehicleSpacing_10", 34 },
    { "VehicleSpacing_11", 27 },
    { "VehicleSpacing_12", 22 },
    { "VehicleSpacing_13", 20 },
    { "VehicleSpacing_14", 19 },
    { "VehicleSpacing_15", 18 },
    { "VehicleSpacing_2", 150 },
    { "VehicleSpacing_3", 129 },
    { "VehicleSpacing_4", 110 },
    { "VehicleSpacing_5", 88 },
    { "VehicleSpacing_6", 55 },
    { "VehicleSpacing_7", 52 },
    { "VehicleSpacing_8", 45 },
    { "VehicleSpacing_9", 40 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 5 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 3 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 测·仅上限 [诊断] ---- */
static const GcKnob GC_PRESET_DIAG_LIMIT_KNOBS[] = {
    { "AmbientPedsMultiplier", 70 },
    { "AmbientPedsMultiplier_Base", 50 },
    { "PedPopulationFrameRate", 25 },
    { "PedPopulationFrameRate_Base", 20 },
    { "PedsForVehicles", 50 },
    { "PedsForVehicles_Base", 50 },
    { "ScenarioPedsMultiplier", 70 },
    { "ScenarioPedsMultiplier_Base", 50 },
    { "VehicleAmbientDensityMultiplier", 70 },
    { "VehicleAmbientDensityMultiplier_Base", 45 },
    { "VehicleLowPrioParkedDensityMultiplier", 50 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 30 },
    { "VehicleParkedDensityMultiplier", 60 },
    { "VehicleParkedDensityMultiplier_Base", 35 },
    { "VehiclePopulationFrameRate", 25 },
    { "VehiclePopulationFrameRate_Base", 20 },
    { "MaxTotalPeds", 35 },
    { "MaxTotalPeds_Base", 32 },
    { "VehicleParkedUpperLimit", 35 },
    { "VehicleParkedUpperLimit_Base", 20 },
    { "VehicleUpperLimit", 34 },
    { "VehicleUpperLimit_Base", 17 },
    { "PedMemoryMultiplier", 150 },
    { "VehicleMemoryMultiplier", 100 },
    { "VehicleSpacing_1", 172 },
    { "VehicleSpacing_10", 34 },
    { "VehicleSpacing_11", 27 },
    { "VehicleSpacing_12", 22 },
    { "VehicleSpacing_13", 20 },
    { "VehicleSpacing_14", 19 },
    { "VehicleSpacing_15", 18 },
    { "VehicleSpacing_2", 150 },
    { "VehicleSpacing_3", 129 },
    { "VehicleSpacing_4", 110 },
    { "VehicleSpacing_5", 88 },
    { "VehicleSpacing_6", 55 },
    { "VehicleSpacing_7", 52 },
    { "VehicleSpacing_8", 45 },
    { "VehicleSpacing_9", 40 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 5 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 3 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 测·仅间距 [诊断] ---- */
static const GcKnob GC_PRESET_DIAG_SPACING_KNOBS[] = {
    { "AmbientPedsMultiplier", 70 },
    { "AmbientPedsMultiplier_Base", 50 },
    { "PedPopulationFrameRate", 25 },
    { "PedPopulationFrameRate_Base", 20 },
    { "PedsForVehicles", 50 },
    { "PedsForVehicles_Base", 50 },
    { "ScenarioPedsMultiplier", 70 },
    { "ScenarioPedsMultiplier_Base", 50 },
    { "VehicleAmbientDensityMultiplier", 70 },
    { "VehicleAmbientDensityMultiplier_Base", 45 },
    { "VehicleLowPrioParkedDensityMultiplier", 50 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 30 },
    { "VehicleParkedDensityMultiplier", 60 },
    { "VehicleParkedDensityMultiplier_Base", 35 },
    { "VehiclePopulationFrameRate", 25 },
    { "VehiclePopulationFrameRate_Base", 20 },
    { "MaxTotalPeds", 50 },
    { "MaxTotalPeds_Base", 45 },
    { "VehicleParkedUpperLimit", 50 },
    { "VehicleParkedUpperLimit_Base", 28 },
    { "VehicleUpperLimit", 48 },
    { "VehicleUpperLimit_Base", 24 },
    { "PedMemoryMultiplier", 150 },
    { "VehicleMemoryMultiplier", 100 },
    { "VehicleSpacing_1", 215 },
    { "VehicleSpacing_10", 43 },
    { "VehicleSpacing_11", 34 },
    { "VehicleSpacing_12", 28 },
    { "VehicleSpacing_13", 25 },
    { "VehicleSpacing_14", 24 },
    { "VehicleSpacing_15", 23 },
    { "VehicleSpacing_2", 188 },
    { "VehicleSpacing_3", 161 },
    { "VehicleSpacing_4", 138 },
    { "VehicleSpacing_5", 110 },
    { "VehicleSpacing_6", 69 },
    { "VehicleSpacing_7", 65 },
    { "VehicleSpacing_8", 56 },
    { "VehicleSpacing_9", 50 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 5 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 3 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 验·人归零 [验证] ---- */
static const GcKnob GC_PRESET_ZERO_PED_KNOBS[] = {
    { "AmbientPedsMultiplier", 0 },
    { "AmbientPedsMultiplier_Base", 0 },
    { "PedPopulationFrameRate", 25 },
    { "PedPopulationFrameRate_Base", 20 },
    { "PedsForVehicles", 0 },
    { "PedsForVehicles_Base", 0 },
    { "ScenarioPedsMultiplier", 0 },
    { "ScenarioPedsMultiplier_Base", 0 },
    { "VehicleAmbientDensityMultiplier", 70 },
    { "VehicleAmbientDensityMultiplier_Base", 45 },
    { "VehicleLowPrioParkedDensityMultiplier", 50 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 30 },
    { "VehicleParkedDensityMultiplier", 60 },
    { "VehicleParkedDensityMultiplier_Base", 35 },
    { "VehiclePopulationFrameRate", 25 },
    { "VehiclePopulationFrameRate_Base", 20 },
    { "MaxTotalPeds", 0 },
    { "MaxTotalPeds_Base", 0 },
    { "VehicleParkedUpperLimit", 50 },
    { "VehicleParkedUpperLimit_Base", 28 },
    { "VehicleUpperLimit", 48 },
    { "VehicleUpperLimit_Base", 24 },
    { "PedMemoryMultiplier", 150 },
    { "VehicleMemoryMultiplier", 100 },
    { "VehicleSpacing_1", 172 },
    { "VehicleSpacing_10", 34 },
    { "VehicleSpacing_11", 27 },
    { "VehicleSpacing_12", 22 },
    { "VehicleSpacing_13", 20 },
    { "VehicleSpacing_14", 19 },
    { "VehicleSpacing_15", 18 },
    { "VehicleSpacing_2", 150 },
    { "VehicleSpacing_3", 129 },
    { "VehicleSpacing_4", 110 },
    { "VehicleSpacing_5", 88 },
    { "VehicleSpacing_6", 55 },
    { "VehicleSpacing_7", 52 },
    { "VehicleSpacing_8", 45 },
    { "VehicleSpacing_9", 40 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 5 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 3 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 验·车归零 [验证] ---- */
static const GcKnob GC_PRESET_ZERO_VEH_KNOBS[] = {
    { "AmbientPedsMultiplier", 70 },
    { "AmbientPedsMultiplier_Base", 50 },
    { "PedPopulationFrameRate", 25 },
    { "PedPopulationFrameRate_Base", 20 },
    { "PedsForVehicles", 50 },
    { "PedsForVehicles_Base", 50 },
    { "ScenarioPedsMultiplier", 70 },
    { "ScenarioPedsMultiplier_Base", 50 },
    { "VehicleAmbientDensityMultiplier", 0 },
    { "VehicleAmbientDensityMultiplier_Base", 0 },
    { "VehicleLowPrioParkedDensityMultiplier", 0 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 0 },
    { "VehicleParkedDensityMultiplier", 0 },
    { "VehicleParkedDensityMultiplier_Base", 0 },
    { "VehiclePopulationFrameRate", 25 },
    { "VehiclePopulationFrameRate_Base", 20 },
    { "MaxTotalPeds", 50 },
    { "MaxTotalPeds_Base", 45 },
    { "VehicleParkedUpperLimit", 0 },
    { "VehicleParkedUpperLimit_Base", 0 },
    { "VehicleUpperLimit", 0 },
    { "VehicleUpperLimit_Base", 0 },
    { "PedMemoryMultiplier", 150 },
    { "VehicleMemoryMultiplier", 100 },
    { "VehicleSpacing_1", 172 },
    { "VehicleSpacing_10", 34 },
    { "VehicleSpacing_11", 27 },
    { "VehicleSpacing_12", 22 },
    { "VehicleSpacing_13", 20 },
    { "VehicleSpacing_14", 19 },
    { "VehicleSpacing_15", 18 },
    { "VehicleSpacing_2", 150 },
    { "VehicleSpacing_3", 129 },
    { "VehicleSpacing_4", 110 },
    { "VehicleSpacing_5", 88 },
    { "VehicleSpacing_6", 55 },
    { "VehicleSpacing_7", 52 },
    { "VehicleSpacing_8", 45 },
    { "VehicleSpacing_9", 40 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 5 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 3 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 验·人车全零 [验证] ---- */
static const GcKnob GC_PRESET_ZERO_ALL_KNOBS[] = {
    { "AmbientPedsMultiplier", 0 },
    { "AmbientPedsMultiplier_Base", 0 },
    { "PedPopulationFrameRate", 0 },
    { "PedPopulationFrameRate_Base", 0 },
    { "PedsForVehicles", 0 },
    { "PedsForVehicles_Base", 0 },
    { "ScenarioPedsMultiplier", 0 },
    { "ScenarioPedsMultiplier_Base", 0 },
    { "VehicleAmbientDensityMultiplier", 0 },
    { "VehicleAmbientDensityMultiplier_Base", 0 },
    { "VehicleLowPrioParkedDensityMultiplier", 0 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 0 },
    { "VehicleParkedDensityMultiplier", 0 },
    { "VehicleParkedDensityMultiplier_Base", 0 },
    { "VehiclePopulationFrameRate", 0 },
    { "VehiclePopulationFrameRate_Base", 0 },
    { "MaxTotalPeds", 0 },
    { "MaxTotalPeds_Base", 0 },
    { "VehicleParkedUpperLimit", 0 },
    { "VehicleParkedUpperLimit_Base", 0 },
    { "VehicleUpperLimit", 0 },
    { "VehicleUpperLimit_Base", 0 },
    { "PedMemoryMultiplier", 150 },
    { "VehicleMemoryMultiplier", 100 },
    { "VehicleSpacing_1", 172 },
    { "VehicleSpacing_10", 34 },
    { "VehicleSpacing_11", 27 },
    { "VehicleSpacing_12", 22 },
    { "VehicleSpacing_13", 20 },
    { "VehicleSpacing_14", 19 },
    { "VehicleSpacing_15", 18 },
    { "VehicleSpacing_2", 150 },
    { "VehicleSpacing_3", 129 },
    { "VehicleSpacing_4", 110 },
    { "VehicleSpacing_5", 88 },
    { "VehicleSpacing_6", 55 },
    { "VehicleSpacing_7", 52 },
    { "VehicleSpacing_8", 45 },
    { "VehicleSpacing_9", 40 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 5 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 3 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* ---- 验·刷新归零 [验证] ---- */
static const GcKnob GC_PRESET_ZERO_RATE_KNOBS[] = {
    { "AmbientPedsMultiplier", 70 },
    { "AmbientPedsMultiplier_Base", 50 },
    { "PedPopulationFrameRate", 0 },
    { "PedPopulationFrameRate_Base", 0 },
    { "PedsForVehicles", 50 },
    { "PedsForVehicles_Base", 50 },
    { "ScenarioPedsMultiplier", 70 },
    { "ScenarioPedsMultiplier_Base", 50 },
    { "VehicleAmbientDensityMultiplier", 70 },
    { "VehicleAmbientDensityMultiplier_Base", 45 },
    { "VehicleLowPrioParkedDensityMultiplier", 50 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", 30 },
    { "VehicleParkedDensityMultiplier", 60 },
    { "VehicleParkedDensityMultiplier_Base", 35 },
    { "VehiclePopulationFrameRate", 0 },
    { "VehiclePopulationFrameRate_Base", 0 },
    { "MaxTotalPeds", 50 },
    { "MaxTotalPeds_Base", 45 },
    { "VehicleParkedUpperLimit", 50 },
    { "VehicleParkedUpperLimit_Base", 28 },
    { "VehicleUpperLimit", 48 },
    { "VehicleUpperLimit_Base", 24 },
    { "PedMemoryMultiplier", 150 },
    { "VehicleMemoryMultiplier", 100 },
    { "VehicleSpacing_1", 172 },
    { "VehicleSpacing_10", 34 },
    { "VehicleSpacing_11", 27 },
    { "VehicleSpacing_12", 22 },
    { "VehicleSpacing_13", 20 },
    { "VehicleSpacing_14", 19 },
    { "VehicleSpacing_15", 18 },
    { "VehicleSpacing_2", 150 },
    { "VehicleSpacing_3", 129 },
    { "VehicleSpacing_4", 110 },
    { "VehicleSpacing_5", 88 },
    { "VehicleSpacing_6", 55 },
    { "VehicleSpacing_7", 52 },
    { "VehicleSpacing_8", 45 },
    { "VehicleSpacing_9", 40 },
    { "VehicleTimesliceMaxUpdatesPerFrame", 5 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", 3 },
    { "ArchiveCount", 3672 },
    { "DensityBasedRemovalRateScale", 36 },
    { "DensityBasedRemovalRateScale_Base", 36 },
    { "DensityBasedRemovalTargetHeadroom", 10 },
    { "DensityBasedRemovalTargetHeadroom_Base", 10 },
    { "MaxBaseModelInfos", 2 },
    { "MaxCompEntityModelInfos", 50 },
    { "MaxDoorExtensions", 45 },
    { "MaxExpressionExtensions", 50 },
    { "MaxExtraPedModelInfos", 100 },
    { "MaxExtraVehicleModelInfos", 100 },
    { "MaxExtraWeaponModelInfos", 100 },
    { "MaxLightExtensions", 1024 },
    { "MaxMloInstances", 15000 },
    { "MaxMloModelInfos", 220 },
    { "MaxPedModelInfos", 725 },
    { "MaxSpawnPointOverrideExtensions", 50 },
    { "MaxTimeModelInfos", 1800 },
    { "MaxVehicleModelInfos", 320 },
    { "MaxWeaponModelInfos", 115 },
    { "PhysicalStreamingBuffer", 2354 },
    { "PlayersRoadScanDistance", 330 },
    { "PlayersRoadScanDistance_Base", 300 },
    { "VehicleCullRange", 220 },
    { "VehicleCullRangeOffScreen", 100 },
    { "VehicleCullRangeOffScreen_Base", 80 },
    { "VehicleCullRangeOnScreenScale", 140 },
    { "VehicleCullRangeOnScreenScale_Base", 140 },
    { "VehicleCullRange_Base", 190 },
    { "VehicleKeyholeShapeInnerRadius", 90 },
    { "VehicleKeyholeShapeInnerRadius_Base", 65 },
    { "VehicleKeyholeShapeOuterRadius", 170 },
    { "VehicleKeyholeShapeOuterRadius_Base", 150 },
    { "VehicleMaxCreationDistance", 200 },
    { "VehicleMaxCreationDistanceOffscreen", 45 },
    { "VehicleMaxCreationDistanceOffscreen_Base", 45 },
    { "VehicleMaxCreationDistance_Base", 170 },
    { "VirtualStreamingBuffer", 0 },
};

/* 预设总表（顺序 = 界面显示顺序） */
static const GcPreset GC_PRESETS[] = {
    { "原版", "官方原始", "移植作者原始参数。点「套用」可把被改过的参数全部还原。",
      "Original", "stock", "The porter's original params. Apply to reset any edited knobs.",
      GC_PRESET_ORIGINAL_KNOBS, 79, -1 },
    { "极限省电", "最省CPU", "密度与刷新率降到最低。画面明显缩水，掌机续航用。",
      "Ultra Save", "lowest CPU", "Density & refresh at minimum. Visible downgrade; handheld battery use.",
      GC_PRESET_ULTRA_SAVE_KNOBS, 79, 0 },
    { "省电", "续航优先", "CPU 明显减负，画面缩水可接受。掌机模式推荐。",
      "Power Save", "battery first", "Clear CPU relief, acceptable visual loss. Recommended handheld.",
      GC_PRESET_POWERSAVE_KNOBS, 79, 16 },
    { "均衡", "最安全", "CPU 与画面兼顾，日常推荐。",
      "Balanced", "safest", "CPU and visuals balanced. Daily recommendation.",
      GC_PRESET_BALANCED_KNOBS, 79, 34 },
    { "均衡+", "推荐", "比原版略省 CPU，画面几乎无感。适合大多数人。",
      "Balanced+", "recommended", "Slightly less CPU than stock, visuals nearly unchanged. Fits most.",
      GC_PRESET_BALANCED_PLUS_KNOBS, 79, 50 },
    { "画质", "画质优先", "略超原版，CPU 开销略增。底座模式可用。",
      "Quality", "visuals first", "Slightly above stock, a bit more CPU. Docked mode.",
      GC_PRESET_QUALITY_KNOBS, 79, 68 },
    { "高画质", "画质优先", "明显高于原版，需要一定超频。",
      "High Quality", "visuals first", "Clearly above stock; needs some overclock.",
      GC_PRESET_HIGH_KNOBS, 79, 84 },
    { "极限", "仅超频机", "全参数放开。仅限极限超频（CPU 2500+ / GPU 1100+）。",
      "Extreme", "OC only", "Everything unlocked. Extreme OC only (CPU 2500+ / GPU 1100+).",
      GC_PRESET_EXTREME_KNOBS, 79, 100 },
    { "测·仅密度", "诊断", "只改 12 项人口密度倍率，其余全原版。此档若快于原版 ⇒ 密度有效。",
      "T: density only", "diag", "Only 12 density multipliers changed. If faster than stock => density matters.",
      GC_PRESET_DIAG_DENSITY_KNOBS, 79, 0 },
    { "测·仅刷新", "诊断", "只改 4 项刷新率，其余全原版。",
      "T: refresh only", "diag", "Only 4 refresh rates changed, rest stock.",
      GC_PRESET_DIAG_RATE_KNOBS, 79, 0 },
    { "测·仅上限", "诊断", "只改 6 项数量上限，其余全原版。",
      "T: limits only", "diag", "Only 6 count limits changed, rest stock.",
      GC_PRESET_DIAG_LIMIT_KNOBS, 79, 0 },
    { "测·仅间距", "诊断", "只改 15 项载具间距，其余全原版。",
      "T: spacing only", "diag", "Only 15 vehicle spacing values changed, rest stock.",
      GC_PRESET_DIAG_SPACING_KNOBS, 79, 0 },
    { "验·人归零", "验证", "把行人相关的 8 项全设 0。若街上完全没人 ⇒ 参数生效。",
      "V: peds zero", "verify", "8 ped-related knobs set to 0. Empty streets => params effective.",
      GC_PRESET_ZERO_PED_KNOBS, 79, 0 },
    { "验·车归零", "验证", "把载具相关的 10 项全设 0。若街上完全没车 ⇒ 参数生效。",
      "V: vehicles zero", "verify", "10 vehicle-related knobs set to 0. Empty roads => params effective.",
      GC_PRESET_ZERO_VEH_KNOBS, 79, 0 },
    { "验·人车全零", "验证", "人+车全部设 0（含刷新率）。街上应彻底空掉 ⇒ 最彻底的生效验证。",
      "V: all zero", "verify", "Peds+vehicles all 0 (incl. refresh). Totally empty streets => strongest verification.",
      GC_PRESET_ZERO_ALL_KNOBS, 79, 0 },
    { "验·刷新归零", "验证", "只把 4 项刷新率设 0（密度不动）。若人车不再移动/刷新 ⇒ 刷新率生效。",
      "V: refresh zero", "verify", "Only 4 refresh rates set to 0 (density untouched). If peds/vehicles stop moving => refresh effective.",
      GC_PRESET_ZERO_RATE_KNOBS, 79, 0 },
};
#define GC_NUM_PRESETS ((int)(sizeof(GC_PRESETS)/sizeof(GC_PRESETS[0])))

/* 预设名 -> 下标 */
enum {
    GC_IDX_ORIGINAL = 0,
    GC_IDX_ULTRA_SAVE = 1,
    GC_IDX_POWERSAVE = 2,
    GC_IDX_BALANCED = 3,
    GC_IDX_BALANCED_PLUS = 4,
    GC_IDX_QUALITY = 5,
    GC_IDX_HIGH = 6,
    GC_IDX_EXTREME = 7,
    GC_IDX_DIAG_DENSITY = 8,
    GC_IDX_DIAG_RATE = 9,
    GC_IDX_DIAG_LIMIT = 10,
    GC_IDX_DIAG_SPACING = 11,
    GC_IDX_ZERO_PED = 12,
    GC_IDX_ZERO_VEH = 13,
    GC_IDX_ZERO_ALL = 14,
    GC_IDX_ZERO_RATE = 15,
};

/* ================================================================ */
/* 手动调整用的旋钮元数据                                          */
/* ★ 按重要性排序：S 级（密度倍率/刷新率）在最前，容量池在最后      */
/* ================================================================ */
typedef struct {
    const char *key;
    const char *cn;
    const char *cn_en;   /* ★ v6.3.2: 英文名（g_lang_en=1 时用） */
    int lo, hi;
    int weight;      /* 1=S最关键 2=A重要 3=B次要 4=C容量池(别调) */
} GcKnobMeta;

static const GcKnobMeta GC_KNOB_META[] = {

    /* ── S 级 · 最关键（每帧生效，实测影响最大） ── */
    { "AmbientPedsMultiplier", "环境行人倍率", "Ambient Peds Mult", 0, 200, 1 },
    { "AmbientPedsMultiplier_Base", "环境行人倍率基数", "Ambient Peds Mult Base", 0, 200, 1 },
    { "PedPopulationFrameRate", "行人刷新率", "Ped Pop FrameRate", 0, 25, 1 },
    { "PedPopulationFrameRate_Base", "行人刷新率基数", "Ped Pop FrameRate Base", 0, 25, 1 },
    { "PedsForVehicles", "载具内行人", "Peds In Vehicles", 0, 100, 1 },
    { "PedsForVehicles_Base", "载具内行人基数", "Peds In Vehicles Base", 0, 100, 1 },
    { "ScenarioPedsMultiplier", "剧情行人倍率", "Scenario Peds Mult", 0, 200, 1 },
    { "ScenarioPedsMultiplier_Base", "剧情行人倍率基数", "Scenario Peds Mult Base", 0, 200, 1 },
    { "VehicleAmbientDensityMultiplier", "环境载具密度", "Ambient Veh Density", 0, 200, 1 },
    { "VehicleAmbientDensityMultiplier_Base", "环境载具密度基数", "Ambient Veh Density Base", 0, 200, 1 },
    { "VehicleLowPrioParkedDensityMultiplier", "低优先停放密度", "Low-Prio Parked Density", 0, 200, 1 },
    { "VehicleLowPrioParkedDensityMultiplier_Base", "低优先停放密度基数", "Low-Prio Parked Base", 0, 200, 1 },
    { "VehicleParkedDensityMultiplier", "停放载具密度", "Parked Veh Density", 0, 200, 1 },
    { "VehicleParkedDensityMultiplier_Base", "停放载具密度基数", "Parked Veh Density Base", 0, 200, 1 },
    { "VehiclePopulationFrameRate", "载具刷新率", "Veh Pop FrameRate", 0, 25, 1 },
    { "VehiclePopulationFrameRate_Base", "载具刷新率基数", "Veh Pop FrameRate Base", 0, 25, 1 },

    /* ── A 级 · 重要（数量上限 / 剔除范围 / 生成距离） ── */
    { "MaxTotalPeds", "最大行人总数", "Max Total Peds", 0, 200, 2 },
    { "MaxTotalPeds_Base", "最大行人基数", "Max Total Peds Base", 0, 200, 2 },
    { "VehicleParkedUpperLimit", "停放载具上限", "Parked Veh Limit", 0, 100, 2 },
    { "VehicleParkedUpperLimit_Base", "停放载具基数", "Parked Veh Limit Base", 0, 100, 2 },
    { "VehicleUpperLimit", "载具上限", "Vehicle Limit", 0, 130, 2 },
    { "VehicleUpperLimit_Base", "载具上限基数", "Vehicle Limit Base", 0, 130, 2 },

    /* ── B 级 · 次要（间距 6-15 / 内存倍率 / 每帧更新） ── */
    { "PedMemoryMultiplier", "行人内存倍率", "Ped Memory Mult", 0, 500, 3 },
    { "VehicleMemoryMultiplier", "载具内存倍率", "Veh Memory Mult", 0, 500, 3 },
    { "VehicleSpacing_1", "载具间距1", "Veh Spacing 1", 0, 500, 3 },
    { "VehicleSpacing_10", "载具间距10", "Veh Spacing 10", 0, 500, 3 },
    { "VehicleSpacing_11", "载具间距11", "Veh Spacing 11", 0, 500, 3 },
    { "VehicleSpacing_12", "载具间距12", "Veh Spacing 12", 0, 500, 3 },
    { "VehicleSpacing_13", "载具间距13", "Veh Spacing 13", 0, 500, 3 },
    { "VehicleSpacing_14", "载具间距14", "Veh Spacing 14", 0, 500, 3 },
    { "VehicleSpacing_15", "载具间距15", "Veh Spacing 15", 0, 500, 3 },
    { "VehicleSpacing_2", "载具间距2", "Veh Spacing 2", 0, 500, 3 },
    { "VehicleSpacing_3", "载具间距3", "Veh Spacing 3", 0, 500, 3 },
    { "VehicleSpacing_4", "载具间距4", "Veh Spacing 4", 0, 500, 3 },
    { "VehicleSpacing_5", "载具间距5", "Veh Spacing 5", 0, 500, 3 },
    { "VehicleSpacing_6", "载具间距6", "Veh Spacing 6", 0, 500, 3 },
    { "VehicleSpacing_7", "载具间距7", "Veh Spacing 7", 0, 500, 3 },
    { "VehicleSpacing_8", "载具间距8", "Veh Spacing 8", 0, 500, 3 },
    { "VehicleSpacing_9", "载具间距9", "Veh Spacing 9", 0, 500, 3 },
    { "VehicleTimesliceMaxUpdatesPerFrame", "载具每帧更新上限", "Veh Timeslice Updates", 0, 10, 3 },
    { "VehicleTimesliceMaxUpdatesPerFrame_Base", "载具每帧更新基数", "Veh Timeslice Base", 0, 10, 3 },

    /* ── C 级 · 容量池 —— ⚠️ 调小会变卡，建议保持原版 ── */
    { "ArchiveCount", "归档数量上限", "Archive Count", 0, 100000, 4 },
    { "DensityBasedRemovalRateScale", "密度剔除速率", "Density Removal Rate", 0, 100, 4 },
    { "DensityBasedRemovalRateScale_Base", "密度剔除速率基数", "Density Removal Base", 0, 100, 4 },
    { "DensityBasedRemovalTargetHeadroom", "密度剔除余量", "Density Removal Headroom", 0, 30, 4 },
    { "DensityBasedRemovalTargetHeadroom_Base", "密度剔除余量基数", "Removal Headroom Base", 0, 30, 4 },
    { "MaxBaseModelInfos", "基础模型信息", "Base Model Infos", 0, 100, 4 },
    { "MaxCompEntityModelInfos", "复合实体模型池", "Comp Entity Pool", 0, 100, 4 },
    { "MaxDoorExtensions", "门扩展池", "Door Ext Pool", 0, 75, 4 },
    { "MaxExpressionExtensions", "表情扩展池", "Expression Ext Pool", 0, 255, 4 },
    { "MaxExtraPedModelInfos", "额外行人模型池", "Extra Ped Model Pool", 0, 315, 4 },
    { "MaxExtraVehicleModelInfos", "额外载具模型池", "Extra Veh Model Pool", 0, 485, 4 },
    { "MaxExtraWeaponModelInfos", "额外武器模型池", "Extra Weapon Pool", 0, 20000, 4 },
    { "MaxLightExtensions", "光源扩展池", "Light Ext Pool", 0, 1024, 4 },
    { "MaxMloInstances", "室内实例上限", "MLO Instances", 0, 18000, 4 },
    { "MaxMloModelInfos", "室内模型信息", "MLO Model Infos", 0, 50000, 4 },
    { "MaxPedModelInfos", "行人模型信息池", "Ped Model Pool", 0, 725, 4 },
    { "MaxSpawnPointOverrideExtensions", "生成点覆盖池", "Spawn Override Pool", 0, 255, 4 },
    { "MaxTimeModelInfos", "时间模型信息", "Time Model Infos", 0, 5000, 4 },
    { "MaxVehicleModelInfos", "载具模型信息池", "Veh Model Pool", 0, 320, 4 },
    { "MaxWeaponModelInfos", "武器模型信息池", "Weapon Model Pool", 0, 20000, 4 },
    { "PhysicalStreamingBuffer", "物理流式缓冲", "Physical Stream Buf", 0, 8192, 4 },
    { "PlayersRoadScanDistance", "玩家道路扫描距离", "Road Scan Distance", 0, 330, 4 },
    { "PlayersRoadScanDistance_Base", "玩家道路扫描距离基数", "Road Scan Base", 0, 330, 4 },
    { "VehicleCullRange", "载具剔除范围", "Veh Cull Range", 0, 311, 4 },
    { "VehicleCullRangeOffScreen", "离屏载具剔除", "Off-Screen Cull", 0, 150, 4 },
    { "VehicleCullRangeOffScreen_Base", "离屏载具剔除基数", "Off-Screen Cull Base", 0, 150, 4 },
    { "VehicleCullRangeOnScreenScale", "屏内载具剔除缩放", "On-Screen Cull Scale", 0, 140, 4 },
    { "VehicleCullRangeOnScreenScale_Base", "屏内载具剔除缩放基数", "On-Screen Cull Base", 0, 140, 4 },
    { "VehicleCullRange_Base", "载具剔除范围基数", "Veh Cull Range Base", 0, 311, 4 },
    { "VehicleKeyholeShapeInnerRadius", "载具生成内半径", "Keyhole Inner Radius", 0, 300, 4 },
    { "VehicleKeyholeShapeInnerRadius_Base", "载具生成内半径基数", "Keyhole Inner Base", 0, 300, 4 },
    { "VehicleKeyholeShapeOuterRadius", "载具生成外半径", "Keyhole Outer Radius", 0, 400, 4 },
    { "VehicleKeyholeShapeOuterRadius_Base", "载具生成外半径基数", "Keyhole Outer Base", 0, 400, 4 },
    { "VehicleMaxCreationDistance", "载具生成距离", "Veh Creation Dist", 0, 255, 4 },
    { "VehicleMaxCreationDistanceOffscreen", "离屏生成距离", "Off-Screen Creation", 0, 50, 4 },
    { "VehicleMaxCreationDistanceOffscreen_Base", "离屏生成距离基数", "Off-Screen Creation Base", 0, 50, 4 },
    { "VehicleMaxCreationDistance_Base", "载具生成距离基数", "Veh Creation Base", 0, 255, 4 },
    { "VirtualStreamingBuffer", "虚拟流式缓冲", "Virtual Stream Buf", 0, 1000, 4 },
};
#define GC_NUM_KNOB_META ((int)(sizeof(GC_KNOB_META)/sizeof(GC_KNOB_META[0])))

/* 权重含义（供参考，UI 已内联标签，无需函数）:
 *   1 = S 关键   密度倍率 / 刷新率 / 密度剔除（每帧生效）
 *   2 = A 重要   数量上限 / 剔除范围 / 生成距离
 *   3 = B 次要   间距 6-15 / 内存倍率 / 每帧更新
 *   4 = C 容量池 调小会更卡，建议别动
 */
#endif /* GC_PRESETS_H */
